Repository redhat-cop/cloud.aws_ops, pull requests merged in 2024-12, with the labels that each got.

#126 Updates to networking role
  changelogs/fragments/2024-12-04_ec2_networking_role_add_options.yml
  roles/ec2_networking_resources/README.md
  roles/ec2_networking_resources/defaults/main.yml
  roles/ec2_networking_resources/meta/argument_specs.yml
  roles/ec2_networking_resources/tasks/create.yml
  roles/ec2_networking_resources/tasks/delete.yml
  roles/ec2_networking_resources/tasks/main.yml
  tests/integration/targets/test_ec2_networking_resources/tasks/main.yml
  tests/integration/targets/test_ec2_networking_resources/tasks/teardown.yml
  tests/integration/targets/test_ec2_networking_resources/tasks/test_all_options.yml
  tests/integration/targets/test_ec2_networking_resources/tasks/test_required_options.yml
Labels: safe to test

#125 Add pattern for creating EC2 instance
  extensions/patterns/configure_ec2/README.md
  extensions/patterns/configure_ec2/exec_env/execution-environment.yml
  extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml
  extensions/patterns/configure_ec2/playbooks/group_vars/all.yml
  extensions/patterns/configure_ec2/playbooks/terminate_ec2_instance.yml
  extensions/patterns/configure_ec2/setup.yml
  extensions/patterns/configure_ec2/template_rhdh/configure_ec2.yml
  extensions/patterns/configure_ec2/template_surveys/create_ec2_instance.yml
  extensions/patterns/configure_ec2/template_surveys/terminate_ec2_instance.yml
Labels: safe to test

#123 Add new manage_ec2_instance role
  roles/manage_ec2_instance/README.md
  roles/manage_ec2_instance/defaults/main.yml
  roles/manage_ec2_instance/meta/argument_specs.yml
  roles/manage_ec2_instance/meta/main.yml
  roles/manage_ec2_instance/tasks/ec2_instance_create_operations.yml
  roles/manage_ec2_instance/tasks/ec2_instance_delete_operations.yml
  roles/manage_ec2_instance/tasks/main.yml
  tests/integration/targets/test_manage_ec2_instance/aliases
  tests/integration/targets/test_manage_ec2_instance/defaults/main.yml
  tests/integration/targets/test_manage_ec2_instance/tasks/main.yml
  tests/integration/targets/test_manage_ec2_instance/tasks/setup.yml
  tests/integration/targets/test_manage_ec2_instance/tasks/teardown.yml
  tests/integration/targets/test_manage_ec2_instance/tasks/test_ec2_all_options.yml
  tests/integration/targets/test_manage_ec2_instance/tasks/test_ec2_required_options.yml
Labels: safe to test, skip-changelog

#129 Add security for keypair creation in configure_ec2 pattern
  extensions/patterns/configure_ec2/README.md
  extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml
  extensions/patterns/configure_ec2/playbooks/group_vars/all.yml
  extensions/patterns/configure_ec2/template_surveys/create_ec2_instance.yml
  roles/manage_ec2_instance/README.md
  roles/manage_ec2_instance/tasks/ec2_instance_create_operations.yml
Labels: mergeit, safe to test, skip-changelog

#130 Small updates to ec2 pattern
  extensions/patterns/configure_ec2/playbooks/create_ec2_instance.yml
  extensions/patterns/configure_ec2/template_surveys/terminate_ec2_instance.yml
  roles/manage_ec2_instance/tasks/ec2_instance_create_operations.yml
Labels: safe to test, skip-changelog
